server:
  port: ${ACCOUNT_SERVER_PORT}

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${ACCOUNT_DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
  rabbitmq:
    addresses: ${RABBITMQ_HOST}:${RABBITMQ_PORT}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    account: account.queue
  routing-keys:
    internal-account: internal.account.routing-key