server:
  port: ${ACCOUNT_SERVER_PORT:8082}

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${ACCOUNT_DATABASE_NAME:account}
    username: ${DATABASE_USER:nebula}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    account: account.queue
  routing-keys:
    internal-account: internal.account.routing-key