server:
  port: ${CUSTOMER_SERVER_PORT}

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${CUSTOMER_DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/
  rabbitmq:
    addresses: ${RABBITMQ_HOST}:${RABBITMQ_PORT}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    account: account.queue
  routing-keys:
    internal-account: internal.account.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true