domain:
  events:
    customer-created: ${CUSTOMER_CREATED_EVENT}
    account-created: ${ACCOUNT_CREATED_EVENT}
    fraud-checked: ${FRAUD_CHECKED_EVENT}

api:
  request-mappings:
    customer-post: ${API_CUSTOMER_POST_PATH}
  clients:
    fraud-check:
      service-name: ${API_FRAUD_CHECK_SERVICE_NAME}
      path: ${API_FRAUD_CHECK_PATH}

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  jackson:
    serialization:
      indent-output: ${JACKSON_SERIALIZATION_INDENT_OUTPUT}
    deserialization:
      fail-on-unknown-properties: ${JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: ${JPA_PROPERTY_HIBERNATE_DIALECT}
        format_sql: ${JPA_PROPERTY_HIBERNATE_FORMAT_SQL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
  zipkin:
    base-url: ${ZIPKIN_URL}
  rabbitmq:
    addresses: ${AMQP_URL}

amqp:
  exchanges:
    internal: ${INTERNAL_EXCHANGE}
  queues:
    customer-created: ${CUSTOMER_CREATED_EVENT}
    account-created: ${ACCOUNT_CREATED_EVENT}
    fraud-checked: ${FRAUD_CHECKED_EVENT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER}