server:
  port: ${CUSTOMER_SERVER_PORT}

spring:
  application:
    name: customer
  jackson:
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://db:${DATABASE_PORT}/${CUSTOMER_DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://zipkin:${ZIPKIN_PORT}/
  rabbitmq:
    addresses: rabbitmq:${RABBITMQ_PORT}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    account: account.queue
  routing-keys:
    internal-account: internal.account.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true