services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./sql/start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - ${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}
    networks:
      - data
    restart: unless-stopped

  db-admin:
    container_name: db-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_ADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${DATABASE_ADMIN_EXTERNAL_PORT}:${DATABASE_ADMIN_INTERNAL_PORT}
    networks:
      - data
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - ${ZIPKIN_EXTERNAL_PORT}:${ZIPKIN_INTERNAL_PORT}
    networks:
      - services

  amqp:
    container_name: amqp
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - ${AMQP_EXTERNAL_PORT}:${AMQP_INTERNAL_PORT}
      - ${AMQP_MANAGEMENT_EXTERNAL_PORT}:${AMQP_MANAGEMENT_INTERNAL_PORT}
    networks:
      - services

  eureka:
    container_name: eureka
    image: daromi94/nebula-eureka
    environment:
      - APPLICATION_NAME=${EUREKA_APPLICATION_NAME}
      - SERVER_PORT=${EUREKA_INTERNAL_PORT}
    ports:
      - ${EUREKA_EXTERNAL_PORT}:${EUREKA_INTERNAL_PORT}
    networks:
      - services

  account:
    container_name: account
    image: daromi94/nebula-account
    environment:
      - CUSTOMER_CREATED_EVENT=${CUSTOMER_CREATED_EVENT}
      - ACCOUNT_CREATED_EVENT=${ACCOUNT_CREATED_EVENT}
      - FRAUD_CHECKED_EVENT=${FRAUD_CHECKED_EVENT}
      - SERVER_PORT=${ACCOUNT_SERVER_INTERNAL_PORT}
      - APPLICATION_NAME=${ACCOUNT_APPLICATION_NAME}
      - JACKSON_SERIALIZATION_INDENT_OUTPUT=${ACCOUNT_JACKSON_SERIALIZATION_INDENT_OUTPUT}
      - JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES=${ACCOUNT_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
      - DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_INTERNAL_PORT}/${ACCOUNT_DATABASE_NAME}
      - DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - JPA_PROPERTY_HIBERNATE_DIALECT=${ACCOUNT_JPA_PROPERTY_HIBERNATE_DIALECT}
      - JPA_PROPERTY_HIBERNATE_FORMAT_SQL=${ACCOUNT_JPA_PROPERTY_HIBERNATE_FORMAT_SQL}
      - JPA_HIBERNATE_DDL_AUTO=${ACCOUNT_JPA_HIBERNATE_DDL_AUTO}
      - JPA_SHOW_SQL=${ACCOUNT_JPA_SHOW_SQL}
      - ZIPKIN_URL=http://zipkin:${ZIPKIN_INTERNAL_PORT}/
      - AMQP_URL=amqp:${AMQP_INTERNAL_PORT}
      - AMQP_INTERNAL_EXCHANGE=${AMQP_INTERNAL_EXCHANGE}
    ports:
      - ${ACCOUNT_SERVER_EXTERNAL_PORT}:${ACCOUNT_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - db
      - amqp
      - zipkin

  customer:
    container_name: customer
    image: daromi94/nebula-customer
    environment:
      - CUSTOMER_CREATED_EVENT=${CUSTOMER_CREATED_EVENT}
      - ACCOUNT_CREATED_EVENT=${ACCOUNT_CREATED_EVENT}
      - FRAUD_CHECKED_EVENT=${FRAUD_CHECKED_EVENT}
      - API_CUSTOMER_POST_PATH=${API_CUSTOMER_POST_PATH}
      - API_FRAUD_CHECK_SERVICE_NAME=${FRAUD_APPLICATION_NAME}
      - API_FRAUD_CHECK_PATH=${API_CLIENT_FRAUD_CHECK_PATH}
      - SERVER_PORT=${CUSTOMER_SERVER_INTERNAL_PORT}
      - APPLICATION_NAME=${CUSTOMER_APPLICATION_NAME}
      - JACKSON_SERIALIZATION_INDENT_OUTPUT=${CUSTOMER_JACKSON_SERIALIZATION_INDENT_OUTPUT}
      - JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES=${CUSTOMER_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
      - DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_INTERNAL_PORT}/${CUSTOMER_DATABASE_NAME}
      - DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - JPA_PROPERTY_HIBERNATE_DIALECT=${CUSTOMER_JPA_PROPERTY_HIBERNATE_DIALECT}
      - JPA_PROPERTY_HIBERNATE_FORMAT_SQL=${CUSTOMER_JPA_PROPERTY_HIBERNATE_FORMAT_SQL}
      - JPA_HIBERNATE_DDL_AUTO=${CUSTOMER_JPA_HIBERNATE_DDL_AUTO}
      - JPA_SHOW_SQL=${CUSTOMER_JPA_SHOW_SQL}
      - ZIPKIN_URL=http://zipkin:${ZIPKIN_INTERNAL_PORT}/
      - AMQP_URL=amqp:${AMQP_INTERNAL_PORT}
      - AMQP_INTERNAL_EXCHANGE=${AMQP_INTERNAL_EXCHANGE}
      - EUREKA_URL=http://eureka:${EUREKA_INTERNAL_PORT}/eureka
      - EUREKA_CLIENT_FETCH_REGISTRY=${CUSTOMER_EUREKA_CLIENT_FETCH_REGISTRY}
      - EUREKA_CLIENT_REGISTER=${CUSTOMER_EUREKA_CLIENT_REGISTER}
    ports:
      - ${CUSTOMER_SERVER_EXTERNAL_PORT}:${CUSTOMER_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - db
      - amqp
      - zipkin
      - eureka

  fraud:
    container_name: fraud
    image: daromi94/nebula-fraud
    environment:
      - CUSTOMER_CREATED_EVENT=${CUSTOMER_CREATED_EVENT}
      - ACCOUNT_CREATED_EVENT=${ACCOUNT_CREATED_EVENT}
      - FRAUD_CHECKED_EVENT=${FRAUD_CHECKED_EVENT}
      - API_FRAUD_CHECK_PATH=${API_CLIENT_FRAUD_CHECK_PATH}
      - SERVER_PORT=${FRAUD_SERVER_INTERNAL_PORT}
      - APPLICATION_NAME=${FRAUD_APPLICATION_NAME}
      - JACKSON_SERIALIZATION_INDENT_OUTPUT=${FRAUD_JACKSON_SERIALIZATION_INDENT_OUTPUT}
      - JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES=${FRAUD_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES}
      - DATASOURCE_URL=jdbc:postgresql://db:${DATABASE_INTERNAL_PORT}/${FRAUD_DATABASE_NAME}
      - DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - JPA_PROPERTY_HIBERNATE_DIALECT=${FRAUD_JPA_PROPERTY_HIBERNATE_DIALECT}
      - JPA_PROPERTY_HIBERNATE_FORMAT_SQL=${FRAUD_JPA_PROPERTY_HIBERNATE_FORMAT_SQL}
      - JPA_HIBERNATE_DDL_AUTO=${FRAUD_JPA_HIBERNATE_DDL_AUTO}
      - JPA_SHOW_SQL=${FRAUD_JPA_SHOW_SQL}
      - ZIPKIN_URL=http://zipkin:${ZIPKIN_INTERNAL_PORT}/
      - AMQP_URL=amqp:${AMQP_INTERNAL_PORT}
      - AMQP_INTERNAL_EXCHANGE=${AMQP_INTERNAL_EXCHANGE}
      - EUREKA_URL=http://eureka:${EUREKA_INTERNAL_PORT}/eureka
      - EUREKA_CLIENT_FETCH_REGISTRY=${FRAUD_EUREKA_CLIENT_FETCH_REGISTRY}
      - EUREKA_CLIENT_REGISTER=${FRAUD_EUREKA_CLIENT_REGISTER}
    ports:
      - ${FRAUD_SERVER_EXTERNAL_PORT}:${FRAUD_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - db
      - amqp
      - zipkin
      - eureka

networks:
  services:
    driver: bridge
  data:
    driver: bridge

volumes:
  postgres:
  pgadmin: