services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
      - ./sql/start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - ${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT:5432}
    networks:
      - data
    restart: unless-stopped

  db-admin:
    container_name: db-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - ${DATABASE_ADMIN_EXTERNAL_PORT}:${DATABASE_ADMIN_INTERNAL_PORT:80}
    networks:
      - data
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - ${ZIPKIN_EXTERNAL_PORT}:${ZIPKIN_INTERNAL_PORT:9411}
    networks:
      - services

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - ${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_INTERNAL_PORT:5672}
      - ${RABBITMQ_MANAGEMENT_EXTERNAL_PORT}:${RABBITMQ_MANAGEMENT_INTERNAL_PORT:15672}
    networks:
      - services

  eureka:
    container_name: eureka
    image: daromi94/nebula-eureka:latest
    environment:
      - EUREKA_PORT=${EUREKA_INTERNAL_PORT}
    ports:
      - ${EUREKA_EXTERNAL_PORT}:${EUREKA_INTERNAL_PORT}
    networks:
      - services

  account:
    container_name: account
    image: daromi94/nebula-account:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_PORT=${DATABASE_INTERNAL_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ACCOUNT_DATABASE_NAME=${ACCOUNT_DATABASE_NAME}
      - ACCOUNT_SERVER_PORT=${ACCOUNT_SERVER_INTERNAL_PORT}
      - ZIPKIN_PORT=${ZIPKIN_INTERNAL_PORT}
      - RABBITMQ_PORT=${RABBITMQ_INTERNAL_PORT}
    ports:
      - ${ACCOUNT_SERVER_EXTERNAL_PORT}:${ACCOUNT_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - data
      - rabbitmq
      - zipkin

  customer:
    container_name: customer
    image: daromi94/nebula-customer:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_PORT=${DATABASE_INTERNAL_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CUSTOMER_DATABASE_NAME=${CUSTOMER_DATABASE_NAME}
      - CUSTOMER_SERVER_PORT=${CUSTOMER_SERVER_INTERNAL_PORT}
      - ZIPKIN_PORT=${ZIPKIN_INTERNAL_PORT}
      - RABBITMQ_PORT=${RABBITMQ_INTERNAL_PORT}
      - EUREKA_PORT=${EUREKA_INTERNAL_PORT}
    ports:
      - ${CUSTOMER_SERVER_EXTERNAL_PORT}:${CUSTOMER_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - data
      - rabbitmq
      - zipkin
      - eureka

  fraud:
    container_name: fraud
    image: daromi94/nebula-fraud:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_PORT=${DATABASE_INTERNAL_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - FRAUD_DATABASE_NAME=${FRAUD_DATABASE_NAME}
      - FRAUD_SERVER_PORT=${FRAUD_SERVER_INTERNAL_PORT}
      - ZIPKIN_PORT=${ZIPKIN_INTERNAL_PORT}
      - EUREKA_PORT=${EUREKA_INTERNAL_PORT}
    ports:
      - ${FRAUD_SERVER_EXTERNAL_PORT}:${FRAUD_SERVER_INTERNAL_PORT}
    networks:
      - services
      - data
    depends_on:
      - data
      - zipkin
      - eureka

networks:
  services:
    driver: bridge
  data:
    driver: bridge

volumes:
  postgres:
  pgadmin: