server:
  port: ${FRAUD_SERVER_PORT}

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://db:${DATABASE_PORT}/${FRAUD_DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://zipkin:${ZIPKIN_PORT}/

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true